# Whether idle players are kicked or not
enabled: true

# Whether debug log messages are displayed to console
verbose: true

# What to do when player is marked as inactive:
# true = Kick from server 
# false = Move to observers
kick-mode: false

# Amount of time (in seconds) before participant is kicked
participant-delay: 90

# Amount of time (in seconds) before observer is kicked
# (only works when kick-mode is true)
observer-delay: 120

# Duration of delay that will feature warning messages (in seconds)
warning-duration: 15

# Frequency between warning countdown messages (in seconds)
warning-frequency: 5

# Allow player bypass with 'idly.bypass' permission
bypass-enabled: true

# When true movement is tracked on pitch/yaw movement only
precise-movement: true

# Types of checks which log activity
checks:
  movement: true
  chat: true
  command: true
  
# Message sent to player when kicked from the server
kick-message: "&c&lYou were kicked for being idle too long!"

# Allow players to be auto-vanished if idle after a configurable period of time
auto-vanish:
  enabled: true
  # Permission node required to auto-vanish when idle
  permission-node: "idly.auto-vanish"
  # Delay - how long a player must be idle for to be considered for auto-vanish
  delay: 600 # Seconds
  # Refresh - how often the auto-vanish task will run
  refresh: 60 # Seconds
  
  
  